package com.rb.fmea.entities;

import java.io.Serializable;

public class ApMonitor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_monitor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_monitor.H_value
     *
     * @mbggenerated
     */
    private Integer hValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_monitor.M_value
     *
     * @mbggenerated
     */
    private Integer mValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_monitor.L_value
     *
     * @mbggenerated
     */
    private Integer lValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_monitor.month
     *
     * @mbggenerated
     */
    private Integer month;

    private int fmeaId;

    public int getFmeaId() {
        return fmeaId;
    }

    public void setFmeaId(int fmeaId) {
        this.fmeaId = fmeaId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ap_monitor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_monitor.id
     *
     * @return the value of ap_monitor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_monitor.id
     *
     * @param id the value for ap_monitor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_monitor.H_value
     *
     * @return the value of ap_monitor.H_value
     *
     * @mbggenerated
     */
    public Integer gethValue() {
        return hValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_monitor.H_value
     *
     * @param hValue the value for ap_monitor.H_value
     *
     * @mbggenerated
     */
    public void sethValue(Integer hValue) {
        this.hValue = hValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_monitor.M_value
     *
     * @return the value of ap_monitor.M_value
     *
     * @mbggenerated
     */
    public Integer getmValue() {
        return mValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_monitor.M_value
     *
     * @param mValue the value for ap_monitor.M_value
     *
     * @mbggenerated
     */
    public void setmValue(Integer mValue) {
        this.mValue = mValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_monitor.L_value
     *
     * @return the value of ap_monitor.L_value
     *
     * @mbggenerated
     */
    public Integer getlValue() {
        return lValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_monitor.L_value
     *
     * @param lValue the value for ap_monitor.L_value
     *
     * @mbggenerated
     */
    public void setlValue(Integer lValue) {
        this.lValue = lValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_monitor.month
     *
     * @return the value of ap_monitor.month
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_monitor.month
     *
     * @param month the value for ap_monitor.month
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_monitor
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", hValue=").append(hValue);
        sb.append(", mValue=").append(mValue);
        sb.append(", lValue=").append(lValue);
        sb.append(", month=").append(month);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}