package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaMilestoneTime implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_milestone_time.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_milestone_time.fmea_plan_start_time
     *
     * @mbggenerated
     */
    private String fmeaPlanStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_milestone_time.fmea_content_start_time
     *
     * @mbggenerated
     */
    private String fmeaContentStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_milestone_time.fmea_analysis_finsh_date
     *
     * @mbggenerated
     */
    private String fmeaAnalysisFinshDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_milestone_time.fmea_action_finsh_date
     *
     * @mbggenerated
     */
    private String fmeaActionFinshDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_milestone_time.fmea_id
     *
     * @mbggenerated
     */
    private Integer fmeaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_milestone_time
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_milestone_time.id
     *
     * @return the value of fmea_milestone_time.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_milestone_time.id
     *
     * @param id the value for fmea_milestone_time.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_milestone_time.fmea_plan_start_time
     *
     * @return the value of fmea_milestone_time.fmea_plan_start_time
     *
     * @mbggenerated
     */
    public String getFmeaPlanStartTime() {
        return fmeaPlanStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_milestone_time.fmea_plan_start_time
     *
     * @param fmeaPlanStartTime the value for fmea_milestone_time.fmea_plan_start_time
     *
     * @mbggenerated
     */
    public void setFmeaPlanStartTime(String fmeaPlanStartTime) {
        this.fmeaPlanStartTime = fmeaPlanStartTime == null ? null : fmeaPlanStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_milestone_time.fmea_content_start_time
     *
     * @return the value of fmea_milestone_time.fmea_content_start_time
     *
     * @mbggenerated
     */
    public String getFmeaContentStartTime() {
        return fmeaContentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_milestone_time.fmea_content_start_time
     *
     * @param fmeaContentStartTime the value for fmea_milestone_time.fmea_content_start_time
     *
     * @mbggenerated
     */
    public void setFmeaContentStartTime(String fmeaContentStartTime) {
        this.fmeaContentStartTime = fmeaContentStartTime == null ? null : fmeaContentStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_milestone_time.fmea_analysis_finsh_date
     *
     * @return the value of fmea_milestone_time.fmea_analysis_finsh_date
     *
     * @mbggenerated
     */
    public String getFmeaAnalysisFinshDate() {
        return fmeaAnalysisFinshDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_milestone_time.fmea_analysis_finsh_date
     *
     * @param fmeaAnalysisFinshDate the value for fmea_milestone_time.fmea_analysis_finsh_date
     *
     * @mbggenerated
     */
    public void setFmeaAnalysisFinshDate(String fmeaAnalysisFinshDate) {
        this.fmeaAnalysisFinshDate = fmeaAnalysisFinshDate == null ? null : fmeaAnalysisFinshDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_milestone_time.fmea_action_finsh_date
     *
     * @return the value of fmea_milestone_time.fmea_action_finsh_date
     *
     * @mbggenerated
     */
    public String getFmeaActionFinshDate() {
        return fmeaActionFinshDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_milestone_time.fmea_action_finsh_date
     *
     * @param fmeaActionFinshDate the value for fmea_milestone_time.fmea_action_finsh_date
     *
     * @mbggenerated
     */
    public void setFmeaActionFinshDate(String fmeaActionFinshDate) {
        this.fmeaActionFinshDate = fmeaActionFinshDate == null ? null : fmeaActionFinshDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_milestone_time.fmea_id
     *
     * @return the value of fmea_milestone_time.fmea_id
     *
     * @mbggenerated
     */
    public Integer getFmeaId() {
        return fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_milestone_time.fmea_id
     *
     * @param fmeaId the value for fmea_milestone_time.fmea_id
     *
     * @mbggenerated
     */
    public void setFmeaId(Integer fmeaId) {
        this.fmeaId = fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_milestone_time
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fmeaPlanStartTime=").append(fmeaPlanStartTime);
        sb.append(", fmeaContentStartTime=").append(fmeaContentStartTime);
        sb.append(", fmeaAnalysisFinshDate=").append(fmeaAnalysisFinshDate);
        sb.append(", fmeaActionFinshDate=").append(fmeaActionFinshDate);
        sb.append(", fmeaId=").append(fmeaId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}