package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaTypeProduct implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_type_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_type_product.fmea_type_id
     *
     * @mbggenerated
     */
    private Integer fmeaTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_type_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_type_product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_type_product.id
     *
     * @return the value of fmea_type_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_type_product.id
     *
     * @param id the value for fmea_type_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_type_product.fmea_type_id
     *
     * @return the value of fmea_type_product.fmea_type_id
     *
     * @mbggenerated
     */
    public Integer getFmeaTypeId() {
        return fmeaTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_type_product.fmea_type_id
     *
     * @param fmeaTypeId the value for fmea_type_product.fmea_type_id
     *
     * @mbggenerated
     */
    public void setFmeaTypeId(Integer fmeaTypeId) {
        this.fmeaTypeId = fmeaTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_type_product.product_id
     *
     * @return the value of fmea_type_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_type_product.product_id
     *
     * @param productId the value for fmea_type_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type_product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fmeaTypeId=").append(fmeaTypeId);
        sb.append(", productId=").append(productId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}