package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaFunction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_function.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_function.function_standard_id
     *
     * @mbggenerated
     */
    private String functionStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_function.function_require
     *
     * @mbggenerated
     */
    private String functionRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_function.fmea_structure_id
     *
     * @mbggenerated
     */
    private Integer fmeaStructureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_function
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_function.id
     *
     * @return the value of fmea_function.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_function.id
     *
     * @param id the value for fmea_function.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public String getFunctionStandard() {
        return functionStandard;
    }

    public void setFunctionStandard(String functionStandard) {
        this.functionStandard = functionStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_function.function_require
     *
     * @return the value of fmea_function.function_require
     *
     * @mbggenerated
     */
    public String getFunctionRequire() {
        return functionRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_function.function_require
     *
     * @param functionRequire the value for fmea_function.function_require
     *
     * @mbggenerated
     */
    public void setFunctionRequire(String functionRequire) {
        this.functionRequire = functionRequire == null ? null : functionRequire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_function.fmea_structure_id
     *
     * @return the value of fmea_function.fmea_structure_id
     *
     * @mbggenerated
     */
    public Integer getFmeaStructureId() {
        return fmeaStructureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_function.fmea_structure_id
     *
     * @param fmeaStructureId the value for fmea_function.fmea_structure_id
     *
     * @mbggenerated
     */
    public void setFmeaStructureId(Integer fmeaStructureId) {
        this.fmeaStructureId = fmeaStructureId;
    }

    @Override
    public String toString() {
        return "FmeaFunction{" +
                "id=" + id +
                ", functionStandard='" + functionStandard + '\'' +
                ", functionRequire='" + functionRequire + '\'' +
                ", fmeaStructureId=" + fmeaStructureId +
                '}';
    }

    public String getFiledName(String fieldName){
        if("functionStandard".equals(fieldName)){
            return "功能描述";
        }else if("functionRequire".equals(fieldName)){
            return "功能要求";
        }else {
            return "";
        }
    }
}