package com.rb.fmea.entities;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
@NoArgsConstructor
@Data
@Accessors(chain = true)
public class FmeaResume implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.structure_name
     *
     * @mbggenerated
     */
    private String structureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.step
     *
     * @mbggenerated
     */
    private String step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.before_change
     *
     * @mbggenerated
     */
    private String beforeChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.after_change
     *
     * @mbggenerated
     */
    private String afterChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.fmea_id
     *
     * @mbggenerated
     */
    private Integer fmeaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", structureName=").append(structureName);
        sb.append(", step=").append(step);
        sb.append(", beforeChange=").append(beforeChange);
        sb.append(", afterChange=").append(afterChange);
        sb.append(", createDate=").append(createDate);
        sb.append(", createBy=").append(createBy);
        sb.append(", desc=").append(desc);
        sb.append(", fmeaId=").append(fmeaId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public FmeaResume(String structureName, String step, String beforeChange, String afterChange, String createDate, String createBy, String desc, Integer fmeaId) {
        this.structureName = structureName;
        this.step = step;
        this.beforeChange = beforeChange;
        this.afterChange = afterChange;
        this.createDate = createDate;
        this.createBy = createBy;
        this.desc = desc;
        this.fmeaId = fmeaId;
    }
}