package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaBasicInformation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.project
     *
     * @mbggenerated
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.fmea_number
     *
     * @mbggenerated
     */
    private String fmeaNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.project_site
     *
     * @mbggenerated
     */
    private String projectSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.fmea_start_time
     *
     * @mbggenerated
     */
    private String fmeaStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.design_response
     *
     * @mbggenerated
     */
    private String designResponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.fmea_update_time
     *
     * @mbggenerated
     */
    private String fmeaUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.level_confident
     *
     * @mbggenerated
     */
    private String levelConfident;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.cross_function_team
     *
     * @mbggenerated
     */
    private String crossFunctionTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_basic_information.fmea_id
     *
     * @mbggenerated
     */
    private Integer fmeaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_basic_information
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.id
     *
     * @return the value of fmea_basic_information.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.id
     *
     * @param id the value for fmea_basic_information.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.company
     *
     * @return the value of fmea_basic_information.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.company
     *
     * @param company the value for fmea_basic_information.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.project
     *
     * @return the value of fmea_basic_information.project
     *
     * @mbggenerated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.project
     *
     * @param project the value for fmea_basic_information.project
     *
     * @mbggenerated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.fmea_number
     *
     * @return the value of fmea_basic_information.fmea_number
     *
     * @mbggenerated
     */
    public String getFmeaNumber() {
        return fmeaNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.fmea_number
     *
     * @param fmeaNumber the value for fmea_basic_information.fmea_number
     *
     * @mbggenerated
     */
    public void setFmeaNumber(String fmeaNumber) {
        this.fmeaNumber = fmeaNumber == null ? null : fmeaNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.project_site
     *
     * @return the value of fmea_basic_information.project_site
     *
     * @mbggenerated
     */
    public String getProjectSite() {
        return projectSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.project_site
     *
     * @param projectSite the value for fmea_basic_information.project_site
     *
     * @mbggenerated
     */
    public void setProjectSite(String projectSite) {
        this.projectSite = projectSite == null ? null : projectSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.fmea_start_time
     *
     * @return the value of fmea_basic_information.fmea_start_time
     *
     * @mbggenerated
     */
    public String getFmeaStartTime() {
        return fmeaStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.fmea_start_time
     *
     * @param fmeaStartTime the value for fmea_basic_information.fmea_start_time
     *
     * @mbggenerated
     */
    public void setFmeaStartTime(String fmeaStartTime) {
        this.fmeaStartTime = fmeaStartTime == null ? null : fmeaStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.design_response
     *
     * @return the value of fmea_basic_information.design_response
     *
     * @mbggenerated
     */
    public String getDesignResponse() {
        return designResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.design_response
     *
     * @param designResponse the value for fmea_basic_information.design_response
     *
     * @mbggenerated
     */
    public void setDesignResponse(String designResponse) {
        this.designResponse = designResponse == null ? null : designResponse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.customer_name
     *
     * @return the value of fmea_basic_information.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.customer_name
     *
     * @param customerName the value for fmea_basic_information.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.fmea_update_time
     *
     * @return the value of fmea_basic_information.fmea_update_time
     *
     * @mbggenerated
     */
    public String getFmeaUpdateTime() {
        return fmeaUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.fmea_update_time
     *
     * @param fmeaUpdateTime the value for fmea_basic_information.fmea_update_time
     *
     * @mbggenerated
     */
    public void setFmeaUpdateTime(String fmeaUpdateTime) {
        this.fmeaUpdateTime = fmeaUpdateTime == null ? null : fmeaUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.level_confident
     *
     * @return the value of fmea_basic_information.level_confident
     *
     * @mbggenerated
     */
    public String getLevelConfident() {
        return levelConfident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.level_confident
     *
     * @param levelConfident the value for fmea_basic_information.level_confident
     *
     * @mbggenerated
     */
    public void setLevelConfident(String levelConfident) {
        this.levelConfident = levelConfident == null ? null : levelConfident.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.platform
     *
     * @return the value of fmea_basic_information.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.platform
     *
     * @param platform the value for fmea_basic_information.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.cross_function_team
     *
     * @return the value of fmea_basic_information.cross_function_team
     *
     * @mbggenerated
     */
    public String getCrossFunctionTeam() {
        return crossFunctionTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.cross_function_team
     *
     * @param crossFunctionTeam the value for fmea_basic_information.cross_function_team
     *
     * @mbggenerated
     */
    public void setCrossFunctionTeam(String crossFunctionTeam) {
        this.crossFunctionTeam = crossFunctionTeam == null ? null : crossFunctionTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_basic_information.fmea_id
     *
     * @return the value of fmea_basic_information.fmea_id
     *
     * @mbggenerated
     */
    public Integer getFmeaId() {
        return fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_basic_information.fmea_id
     *
     * @param fmeaId the value for fmea_basic_information.fmea_id
     *
     * @mbggenerated
     */
    public void setFmeaId(Integer fmeaId) {
        this.fmeaId = fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_basic_information
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", company=").append(company);
        sb.append(", project=").append(project);
        sb.append(", fmeaNumber=").append(fmeaNumber);
        sb.append(", projectSite=").append(projectSite);
        sb.append(", fmeaStartTime=").append(fmeaStartTime);
        sb.append(", designResponse=").append(designResponse);
        sb.append(", customerName=").append(customerName);
        sb.append(", fmeaUpdateTime=").append(fmeaUpdateTime);
        sb.append(", levelConfident=").append(levelConfident);
        sb.append(", platform=").append(platform);
        sb.append(", crossFunctionTeam=").append(crossFunctionTeam);
        sb.append(", fmeaId=").append(fmeaId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}