package com.rb.fmea.entities;

import lombok.NoArgsConstructor;

import java.io.Serializable;
@NoArgsConstructor
public class FmeaResume implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.structure_name
     *
     * @mbggenerated
     */
    private String structureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.step
     *
     * @mbggenerated
     */
    private String step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.before_change
     *
     * @mbggenerated
     */
    private String beforeChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.after_change
     *
     * @mbggenerated
     */
    private String afterChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_resume.fmea_id
     *
     * @mbggenerated
     */
    private Integer fmeaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.id
     *
     * @return the value of fmea_resume.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.id
     *
     * @param id the value for fmea_resume.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.structure_name
     *
     * @return the value of fmea_resume.structure_name
     *
     * @mbggenerated
     */
    public String getStructureName() {
        return structureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.structure_name
     *
     * @param structureName the value for fmea_resume.structure_name
     *
     * @mbggenerated
     */
    public void setStructureName(String structureName) {
        this.structureName = structureName == null ? null : structureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.step
     *
     * @return the value of fmea_resume.step
     *
     * @mbggenerated
     */
    public String getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.step
     *
     * @param step the value for fmea_resume.step
     *
     * @mbggenerated
     */
    public void setStep(String step) {
        this.step = step == null ? null : step.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.before_change
     *
     * @return the value of fmea_resume.before_change
     *
     * @mbggenerated
     */
    public String getBeforeChange() {
        return beforeChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.before_change
     *
     * @param beforeChange the value for fmea_resume.before_change
     *
     * @mbggenerated
     */
    public void setBeforeChange(String beforeChange) {
        this.beforeChange = beforeChange == null ? null : beforeChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.after_change
     *
     * @return the value of fmea_resume.after_change
     *
     * @mbggenerated
     */
    public String getAfterChange() {
        return afterChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.after_change
     *
     * @param afterChange the value for fmea_resume.after_change
     *
     * @mbggenerated
     */
    public void setAfterChange(String afterChange) {
        this.afterChange = afterChange == null ? null : afterChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.create_date
     *
     * @return the value of fmea_resume.create_date
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.create_date
     *
     * @param createDate the value for fmea_resume.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.create_by
     *
     * @return the value of fmea_resume.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.create_by
     *
     * @param createBy the value for fmea_resume.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.desc
     *
     * @return the value of fmea_resume.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.desc
     *
     * @param desc the value for fmea_resume.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_resume.fmea_id
     *
     * @return the value of fmea_resume.fmea_id
     *
     * @mbggenerated
     */
    public Integer getFmeaId() {
        return fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_resume.fmea_id
     *
     * @param fmeaId the value for fmea_resume.fmea_id
     *
     * @mbggenerated
     */
    public void setFmeaId(Integer fmeaId) {
        this.fmeaId = fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", structureName=").append(structureName);
        sb.append(", step=").append(step);
        sb.append(", beforeChange=").append(beforeChange);
        sb.append(", afterChange=").append(afterChange);
        sb.append(", createDate=").append(createDate);
        sb.append(", createBy=").append(createBy);
        sb.append(", desc=").append(desc);
        sb.append(", fmeaId=").append(fmeaId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public FmeaResume(String structureName, String step, String beforeChange, String afterChange, String createDate, String createBy, String desc, Integer fmeaId) {
        this.structureName = structureName;
        this.step = step;
        this.beforeChange = beforeChange;
        this.afterChange = afterChange;
        this.createDate = createDate;
        this.createBy = createBy;
        this.desc = desc;
        this.fmeaId = fmeaId;
    }
}