package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaAp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.ap_value
     *
     * @mbggenerated
     */
    private Double apValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.fail_analysis_id
     *
     * @mbggenerated
     */
    private Integer failAnalysisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.detection_degree
     *
     * @mbggenerated
     */
    private Double detectionDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.frequency_degree
     *
     * @mbggenerated
     */
    private Double frequencyDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.severity
     *
     * @mbggenerated
     */
    private String severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.id
     *
     * @return the value of fmea_ap.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.id
     *
     * @param id the value for fmea_ap.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.ap_value
     *
     * @return the value of fmea_ap.ap_value
     *
     * @mbggenerated
     */
    public Double getApValue() {
        return apValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.ap_value
     *
     * @param apValue the value for fmea_ap.ap_value
     *
     * @mbggenerated
     */
    public void setApValue(Double apValue) {
        this.apValue = apValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.fail_analysis_id
     *
     * @return the value of fmea_ap.fail_analysis_id
     *
     * @mbggenerated
     */
    public Integer getFailAnalysisId() {
        return failAnalysisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.fail_analysis_id
     *
     * @param failAnalysisId the value for fmea_ap.fail_analysis_id
     *
     * @mbggenerated
     */
    public void setFailAnalysisId(Integer failAnalysisId) {
        this.failAnalysisId = failAnalysisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.detection_degree
     *
     * @return the value of fmea_ap.detection_degree
     *
     * @mbggenerated
     */
    public Double getDetectionDegree() {
        return detectionDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.detection_degree
     *
     * @param detectionDegree the value for fmea_ap.detection_degree
     *
     * @mbggenerated
     */
    public void setDetectionDegree(Double detectionDegree) {
        this.detectionDegree = detectionDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.frequency_degree
     *
     * @return the value of fmea_ap.frequency_degree
     *
     * @mbggenerated
     */
    public Double getFrequencyDegree() {
        return frequencyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.frequency_degree
     *
     * @param frequencyDegree the value for fmea_ap.frequency_degree
     *
     * @mbggenerated
     */
    public void setFrequencyDegree(Double frequencyDegree) {
        this.frequencyDegree = frequencyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.severity
     *
     * @return the value of fmea_ap.severity
     *
     * @mbggenerated
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.severity
     *
     * @param severity the value for fmea_ap.severity
     *
     * @mbggenerated
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", apValue=").append(apValue);
        sb.append(", failAnalysisId=").append(failAnalysisId);
        sb.append(", detectionDegree=").append(detectionDegree);
        sb.append(", frequencyDegree=").append(frequencyDegree);
        sb.append(", severity=").append(severity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}