package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaMeasures implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.fmea_measures_standard_id
     *
     * @mbggenerated
     */
    private Integer fmeaMeasuresStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.fmea_measures_desc
     *
     * @mbggenerated
     */
    private String fmeaMeasuresDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.frequency_degree
     *
     * @mbggenerated
     */
    private Double frequencyDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.fmea_measures_category
     *
     * @mbggenerated
     */
    private Integer fmeaMeasuresCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.optimize_measures
     *
     * @mbggenerated
     */
    private Integer optimizeMeasures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.fmea_fail_analysis_id
     *
     * @mbggenerated
     */
    private Integer fmeaFailAnalysisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.charge_name
     *
     * @mbggenerated
     */
    private String chargeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.finsh_date
     *
     * @mbggenerated
     */
    private String finshDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.take_measures
     *
     * @mbggenerated
     */
    private String takeMeasures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_measures.finsh_time
     *
     * @mbggenerated
     */
    private String finshTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_measures
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.id
     *
     * @return the value of fmea_measures.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.id
     *
     * @param id the value for fmea_measures.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.fmea_measures_desc
     *
     * @return the value of fmea_measures.fmea_measures_desc
     *
     * @mbggenerated
     */
    public String getFmeaMeasuresDesc() {
        return fmeaMeasuresDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.fmea_measures_desc
     *
     * @param fmeaMeasuresDesc the value for fmea_measures.fmea_measures_desc
     *
     * @mbggenerated
     */
    public void setFmeaMeasuresDesc(String fmeaMeasuresDesc) {
        this.fmeaMeasuresDesc = fmeaMeasuresDesc == null ? null : fmeaMeasuresDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.frequency_degree
     *
     * @return the value of fmea_measures.frequency_degree
     *
     * @mbggenerated
     */
    public Double getFrequencyDegree() {
        return frequencyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.frequency_degree
     *
     * @param frequencyDegree the value for fmea_measures.frequency_degree
     *
     * @mbggenerated
     */
    public void setFrequencyDegree(Double frequencyDegree) {
        this.frequencyDegree = frequencyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.fmea_measures_category
     *
     * @return the value of fmea_measures.fmea_measures_category
     *
     * @mbggenerated
     */
    public Integer getFmeaMeasuresCategory() {
        return fmeaMeasuresCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.fmea_measures_category
     *
     * @param fmeaMeasuresCategory the value for fmea_measures.fmea_measures_category
     *
     * @mbggenerated
     */
    public void setFmeaMeasuresCategory(Integer fmeaMeasuresCategory) {
        this.fmeaMeasuresCategory = fmeaMeasuresCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.optimize_measures
     *
     * @return the value of fmea_measures.optimize_measures
     *
     * @mbggenerated
     */
    public Integer getOptimizeMeasures() {
        return optimizeMeasures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.optimize_measures
     *
     * @param optimizeMeasures the value for fmea_measures.optimize_measures
     *
     * @mbggenerated
     */
    public void setOptimizeMeasures(Integer optimizeMeasures) {
        this.optimizeMeasures = optimizeMeasures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.fmea_fail_analysis_id
     *
     * @return the value of fmea_measures.fmea_fail_analysis_id
     *
     * @mbggenerated
     */
    public Integer getFmeaFailAnalysisId() {
        return fmeaFailAnalysisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.fmea_fail_analysis_id
     *
     * @param fmeaFailAnalysisId the value for fmea_measures.fmea_fail_analysis_id
     *
     * @mbggenerated
     */
    public void setFmeaFailAnalysisId(Integer fmeaFailAnalysisId) {
        this.fmeaFailAnalysisId = fmeaFailAnalysisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.charge_name
     *
     * @return the value of fmea_measures.charge_name
     *
     * @mbggenerated
     */
    public String getChargeName() {
        return chargeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.charge_name
     *
     * @param chargeName the value for fmea_measures.charge_name
     *
     * @mbggenerated
     */
    public void setChargeName(String chargeName) {
        this.chargeName = chargeName == null ? null : chargeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.finsh_date
     *
     * @return the value of fmea_measures.finsh_date
     *
     * @mbggenerated
     */
    public String getFinshDate() {
        return finshDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.finsh_date
     *
     * @param finshDate the value for fmea_measures.finsh_date
     *
     * @mbggenerated
     */
    public void setFinshDate(String finshDate) {
        this.finshDate = finshDate == null ? null : finshDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.state
     *
     * @return the value of fmea_measures.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.state
     *
     * @param state the value for fmea_measures.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.take_measures
     *
     * @return the value of fmea_measures.take_measures
     *
     * @mbggenerated
     */
    public String getTakeMeasures() {
        return takeMeasures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.take_measures
     *
     * @param takeMeasures the value for fmea_measures.take_measures
     *
     * @mbggenerated
     */
    public void setTakeMeasures(String takeMeasures) {
        this.takeMeasures = takeMeasures == null ? null : takeMeasures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_measures.finsh_time
     *
     * @return the value of fmea_measures.finsh_time
     *
     * @mbggenerated
     */
    public String getFinshTime() {
        return finshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_measures.finsh_time
     *
     * @param finshTime the value for fmea_measures.finsh_time
     *
     * @mbggenerated
     */
    public void setFinshTime(String finshTime) {
        this.finshTime = finshTime == null ? null : finshTime.trim();
    }

    @Override
    public String toString() {
        return "FmeaMeasures{" +
                "id=" + id +
                ", fmeaMeasuresStandard=" + fmeaMeasuresStandard +
                ", fmeaMeasuresDesc='" + fmeaMeasuresDesc + '\'' +
                ", frequencyDegree=" + frequencyDegree +
                ", fmeaMeasuresCategory=" + fmeaMeasuresCategory +
                ", optimizeMeasures=" + optimizeMeasures +
                ", fmeaFailAnalysisId=" + fmeaFailAnalysisId +
                ", chargeName='" + chargeName + '\'' +
                ", finshDate='" + finshDate + '\'' +
                ", state=" + state +
                ", takeMeasures='" + takeMeasures + '\'' +
                ", finshTime='" + finshTime + '\'' +
                '}';
    }

    public Integer getFmeaMeasuresStandard() {
        return fmeaMeasuresStandard;
    }

    public void setFmeaMeasuresStandard(Integer fmeaMeasuresStandard) {
        this.fmeaMeasuresStandard = fmeaMeasuresStandard;
    }
}