package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaFailAnalysisRelate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis_relate.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis_relate.fail_analysis_superior_id
     *
     * @mbggenerated
     */
    private Integer failAnalysisSuperiorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis_relate.fail_analysis__next_id
     *
     * @mbggenerated
     */
    private Integer failAnalysisNextId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_fail_analysis_relate
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_fail_analysis_relate.id
     *
     * @return the value of fmea_fail_analysis_relate.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_fail_analysis_relate.id
     *
     * @param id the value for fmea_fail_analysis_relate.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_fail_analysis_relate.fail_analysis_superior_id
     *
     * @return the value of fmea_fail_analysis_relate.fail_analysis_superior_id
     *
     * @mbggenerated
     */
    public Integer getFailAnalysisSuperiorId() {
        return failAnalysisSuperiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_fail_analysis_relate.fail_analysis_superior_id
     *
     * @param failAnalysisSuperiorId the value for fmea_fail_analysis_relate.fail_analysis_superior_id
     *
     * @mbggenerated
     */
    public void setFailAnalysisSuperiorId(Integer failAnalysisSuperiorId) {
        this.failAnalysisSuperiorId = failAnalysisSuperiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_fail_analysis_relate.fail_analysis__next_id
     *
     * @return the value of fmea_fail_analysis_relate.fail_analysis__next_id
     *
     * @mbggenerated
     */
    public Integer getFailAnalysisNextId() {
        return failAnalysisNextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_fail_analysis_relate.fail_analysis__next_id
     *
     * @param failAnalysisNextId the value for fmea_fail_analysis_relate.fail_analysis__next_id
     *
     * @mbggenerated
     */
    public void setFailAnalysisNextId(Integer failAnalysisNextId) {
        this.failAnalysisNextId = failAnalysisNextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis_relate
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", failAnalysisSuperiorId=").append(failAnalysisSuperiorId);
        sb.append(", failAnalysisNextId=").append(failAnalysisNextId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}