package com.rb.fmea.entities;

import java.io.Serializable;

public class Fmea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea.fmea_name
     *
     * @mbggenerated
     */
    private String fmeaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea.fmea_desc
     *
     * @mbggenerated
     */
    private String fmeaDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea.superior_id
     *
     * @mbggenerated
     */
    private Integer superiorId;

    private int typeId;

    //0表示未完成，1表示完成
    private int state;

    private String finishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public String getFinishDate() {
        return finishDate;
    }

    public void setFinishDate(String finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea.id
     *
     * @return the value of fmea.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea.id
     *
     * @param id the value for fmea.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea.fmea_name
     *
     * @return the value of fmea.fmea_name
     *
     * @mbggenerated
     */
    public String getFmeaName() {
        return fmeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea.fmea_name
     *
     * @param fmeaName the value for fmea.fmea_name
     *
     * @mbggenerated
     */
    public void setFmeaName(String fmeaName) {
        this.fmeaName = fmeaName == null ? null : fmeaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea.fmea_desc
     *
     * @return the value of fmea.fmea_desc
     *
     * @mbggenerated
     */
    public String getFmeaDesc() {
        return fmeaDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea.fmea_desc
     *
     * @param fmeaDesc the value for fmea.fmea_desc
     *
     * @mbggenerated
     */
    public void setFmeaDesc(String fmeaDesc) {
        this.fmeaDesc = fmeaDesc == null ? null : fmeaDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea.product_id
     *
     * @return the value of fmea.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea.product_id
     *
     * @param productId the value for fmea.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea.superior_id
     *
     * @return the value of fmea.superior_id
     *
     * @mbggenerated
     */
    public Integer getSuperiorId() {
        return superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea.superior_id
     *
     * @param superiorId the value for fmea.superior_id
     *
     * @mbggenerated
     */
    public void setSuperiorId(Integer superiorId) {
        this.superiorId = superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fmeaName=").append(fmeaName);
        sb.append(", fmeaDesc=").append(fmeaDesc);
        sb.append(", productId=").append(productId);
        sb.append(", superiorId=").append(superiorId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }
}