package com.rb.fmea.entities;

import lombok.Getter;

import java.io.Serializable;
public class FmeaFailAnalysis implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis.analysis_standard_id
     *
     * @mbggenerated
     */
    private String analysisStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis.fmea_fail_analysis_desc
     *
     * @mbggenerated
     */
    private String fmeaFailAnalysisDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis.function_id
     *
     * @mbggenerated
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_fail_analysis.severity
     *
     * @mbggenerated
     */
    private Integer severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_fail_analysis
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_fail_analysis.id
     *
     * @return the value of fmea_fail_analysis.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_fail_analysis.id
     *
     * @param id the value for fmea_fail_analysis.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_fail_analysis.analysis_standard_id
     *
     * @return the value of fmea_fail_analysis.analysis_standard_id
     *
     * @mbggenerated
     */
    public String getAnalysisStandard() {
        return analysisStandard;
    }

    public void setAnalysisStandard(String analysisStandard) {
        this.analysisStandard = analysisStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_fail_analysis.fmea_fail_analysis_desc
     *
     * @return the value of fmea_fail_analysis.fmea_fail_analysis_desc
     *
     * @mbggenerated
     */
    public String getFmeaFailAnalysisDesc() {
        return fmeaFailAnalysisDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_fail_analysis.fmea_fail_analysis_desc
     *
     * @param fmeaFailAnalysisDesc the value for fmea_fail_analysis.fmea_fail_analysis_desc
     *
     * @mbggenerated
     */
    public void setFmeaFailAnalysisDesc(String fmeaFailAnalysisDesc) {
        this.fmeaFailAnalysisDesc = fmeaFailAnalysisDesc == null ? null : fmeaFailAnalysisDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_fail_analysis.function_id
     *
     * @return the value of fmea_fail_analysis.function_id
     *
     * @mbggenerated
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_fail_analysis.function_id
     *
     * @param functionId the value for fmea_fail_analysis.function_id
     *
     * @mbggenerated
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    public Integer getSeverity() {
        return severity;
    }

    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    public String getName(String fieldName){
        if("fmeaFailAnalysisDesc".equals(fieldName)){
            return "失效模式";
        }else if("severity".equals(fieldName)){
            return "严重度";
        }else{
            return "";
        }
    }
}