package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaFunctionRelate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_function_relate.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_function_relate.function_superior_id
     *
     * @mbggenerated
     */
    private Integer functionSuperiorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_function_relate.function_next_id
     *
     * @mbggenerated
     */
    private Integer functionNextId;


    private Integer fmea_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_function_relate
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_function_relate.id
     *
     * @return the value of fmea_function_relate.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    public Integer getFmea_id() {
        return fmea_id;
    }

    public void setFmea_id(Integer fmea_id) {
        this.fmea_id = fmea_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_function_relate.id
     *
     * @param id the value for fmea_function_relate.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_function_relate.function_superior_id
     *
     * @return the value of fmea_function_relate.function_superior_id
     *
     * @mbggenerated
     */
    public Integer getFunctionSuperiorId() {
        return functionSuperiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_function_relate.function_superior_id
     *
     * @param functionSuperiorId the value for fmea_function_relate.function_superior_id
     *
     * @mbggenerated
     */
    public void setFunctionSuperiorId(Integer functionSuperiorId) {
        this.functionSuperiorId = functionSuperiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_function_relate.function_next_id
     *
     * @return the value of fmea_function_relate.function_next_id
     *
     * @mbggenerated
     */
    public Integer getFunctionNextId() {
        return functionNextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_function_relate.function_next_id
     *
     * @param functionNextId the value for fmea_function_relate.function_next_id
     *
     * @mbggenerated
     */
    public void setFunctionNextId(Integer functionNextId) {
        this.functionNextId = functionNextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_function_relate
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", functionSuperiorId=").append(functionSuperiorId);
        sb.append(", functionNextId=").append(functionNextId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}