package com.rb.fmea.entities;

import java.io.Serializable;

public class FmeaAp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.ap_value
     *
     * @mbggenerated
     */
    private String apValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.fail_analysis_id
     *
     * @mbggenerated
     */
    private Integer failAnalysisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.detection_degree
     *
     * @mbggenerated
     */
    private int detectionDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.frequency_degree
     *
     * @mbggenerated
     */
    private int frequencyDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.severity
     *
     * @mbggenerated
     */
    private int severity;


    private String optApValue;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.detection_degree
     *
     * @mbggenerated
     */
    private int optDetectionDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fmea_ap.frequency_degree
     *
     * @mbggenerated
     */
    private int optFrequencyDegree;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.id
     *
     * @return the value of fmea_ap.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.id
     *
     * @param id the value for fmea_ap.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fmea_ap.fail_analysis_id
     *
     * @return the value of fmea_ap.fail_analysis_id
     *
     * @mbggenerated
     */
    public Integer getFailAnalysisId() {
        return failAnalysisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fmea_ap.fail_analysis_id
     *
     * @param failAnalysisId the value for fmea_ap.fail_analysis_id
     *
     * @mbggenerated
     */
    public void setFailAnalysisId(Integer failAnalysisId) {
        this.failAnalysisId = failAnalysisId;
    }

    public String getApValue() {
        return apValue;
    }

    public void setApValue(String apValue) {
        this.apValue = apValue;
    }

    public int getDetectionDegree() {
        return detectionDegree;
    }

    public void setDetectionDegree(int detectionDegree) {
        this.detectionDegree = detectionDegree;
    }

    public int getFrequencyDegree() {
        return frequencyDegree;
    }

    public void setFrequencyDegree(int frequencyDegree) {
        this.frequencyDegree = frequencyDegree;
    }

    public int getSeverity() {
        return severity;
    }

    public void setSeverity(int severity) {
        this.severity = severity;
    }

    public int getOptDetectionDegree() {
        return optDetectionDegree;
    }

    public void setOptDetectionDegree(int optDetectionDegree) {
        this.optDetectionDegree = optDetectionDegree;
    }

    public int getOptFrequencyDegree() {
        return optFrequencyDegree;
    }

    public void setOptFrequencyDegree(int optFrequencyDegree) {
        this.optFrequencyDegree = optFrequencyDegree;
    }

    public String getOptApValue() {
        return optApValue;
    }

    public void setOptApValue(String optApValue) {
        this.optApValue = optApValue;
    }
}