package com.rb.fmea.entities;

import java.io.Serializable;

public class FunctionStandard implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_standard.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_standard.verb
     *
     * @mbggenerated
     */
    private String verb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_standard.moun
     *
     * @mbggenerated
     */
    private String moun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_standard.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function_standard.integrate
     *
     * @mbggenerated
     */
    private String integrate;

    /**
     * @Author yyk
     * 0表示功能，1表示失效分析，2表示措施
     *
     */
    private int type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table function_standard
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_standard.id
     *
     * @return the value of function_standard.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_standard.id
     *
     * @param id the value for function_standard.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_standard.verb
     *
     * @return the value of function_standard.verb
     *
     * @mbggenerated
     */
    public String getVerb() {
        return verb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_standard.verb
     *
     * @param verb the value for function_standard.verb
     *
     * @mbggenerated
     */
    public void setVerb(String verb) {
        this.verb = verb == null ? null : verb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_standard.moun
     *
     * @return the value of function_standard.moun
     *
     * @mbggenerated
     */
    public String getMoun() {
        return moun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_standard.moun
     *
     * @param moun the value for function_standard.moun
     *
     * @mbggenerated
     */
    public void setMoun(String moun) {
        this.moun = moun == null ? null : moun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_standard.desc
     *
     * @return the value of function_standard.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_standard.desc
     *
     * @param desc the value for function_standard.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function_standard.integrate
     *
     * @return the value of function_standard.integrate
     *
     * @mbggenerated
     */
    public String getIntegrate() {
        return integrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function_standard.integrate
     *
     * @param integrate the value for function_standard.integrate
     *
     * @mbggenerated
     */
    public void setIntegrate(String integrate) {
        this.integrate = integrate == null ? null : integrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_standard
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", verb=").append(verb);
        sb.append(", moun=").append(moun);
        sb.append(", desc=").append(desc);
        sb.append(", integrate=").append(integrate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }
}