package com.rb.fmea.entities;

import java.io.Serializable;

public class MeasuresMonitor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measures _monitor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measures _monitor.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measures _monitor.month
     *
     * @mbggenerated
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measures _monitor.fmea_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measures _monitor.total_num
     *
     * @mbggenerated
     */
    private Integer totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table measures _monitor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measures _monitor.id
     *
     * @return the value of measures _monitor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measures _monitor.id
     *
     * @param id the value for measures _monitor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measures _monitor.level
     *
     * @return the value of measures _monitor.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measures _monitor.level
     *
     * @param level the value for measures _monitor.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measures _monitor.month
     *
     * @return the value of measures _monitor.month
     *
     * @mbggenerated
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measures _monitor.month
     *
     * @param month the value for measures _monitor.month
     *
     * @mbggenerated
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measures _monitor.total_num
     *
     * @return the value of measures _monitor.total_num
     *
     * @mbggenerated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measures _monitor.total_num
     *
     * @param totalNum the value for measures _monitor.total_num
     *
     * @mbggenerated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }


}