package com.rb.fmea.entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.io.Serializable;
@Data
@AllArgsConstructor
@NoArgsConstructor
@Accessors(chain = true)
public class Review implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_require
     *
     * @mbggenerated
     */
    private String reviewRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.special_require
     *
     * @mbggenerated
     */
    private String specialRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.finsh_date
     *
     * @mbggenerated
     */
    private String finshDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.fmea_id
     *
     * @mbggenerated
     */
    private Integer fmeaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.responsible
     *
     * @mbggenerated
     */
    private String responsible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.step
     *表示对应的结构id
     * @mbggenerated
     */
    private Integer step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_result
     *
     * @mbggenerated
     */
    private String reviewResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_date
     *
     * @mbggenerated
     */
    private String reviewDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.create_date
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.state
     *0表示总成，1表示零件
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_state
     *0表示未建计划，1表示待实施，2表示已完成，3表示计划未建超期，4表示未评审超期
     * @mbggenerated
     */
    private Integer reviewState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", reviewRequire=").append(reviewRequire);
        sb.append(", specialRequire=").append(specialRequire);
        sb.append(", finshDate=").append(finshDate);
        sb.append(", fmeaId=").append(fmeaId);
        sb.append(", responsible=").append(responsible);
        sb.append(", step=").append(step);
        sb.append(", reviewResult=").append(reviewResult);
        sb.append(", reviewDate=").append(reviewDate);
        sb.append(", createDate=").append(createDate);
        sb.append(", state=").append(state);
        sb.append(", reviewState=").append(reviewState);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}