package com.rb.fmea.entities;

import java.io.Serializable;

public class ReviewResult implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_result.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_result.function_review_result
     *0表示待建，1表示计划，2表示完成，3表示待建超期，4表示计划超期
     * @mbggenerated
     */
    private Integer functionReviewResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_result.fail_analysis_review_result
     *0表示待建，1表示计划，2表示完成，3表示待建超期，4表示计划超期
     * @mbggenerated
     */
    private Integer failAnalysisReviewResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_result.risk_review_result
     *0表示待建，1表示计划，2表示完成，3表示待建超期，4表示计划超期
     * @mbggenerated
     */
    private Integer riskReviewResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review_result.fmea_id
     *
     * @mbggenerated
     */
    private Integer fmeaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review_result
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_result.id
     *
     * @return the value of review_result.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_result.id
     *
     * @param id the value for review_result.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_result.function_review_result
     *
     * @return the value of review_result.function_review_result
     *
     * @mbggenerated
     */
    public Integer getFunctionReviewResult() {
        return functionReviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_result.function_review_result
     *
     * @param functionReviewResult the value for review_result.function_review_result
     *
     * @mbggenerated
     */
    public void setFunctionReviewResult(Integer functionReviewResult) {
        this.functionReviewResult = functionReviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_result.fail_analysis_review_result
     *
     * @return the value of review_result.fail_analysis_review_result
     *
     * @mbggenerated
     */
    public Integer getFailAnalysisReviewResult() {
        return failAnalysisReviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_result.fail_analysis_review_result
     *
     * @param failAnalysisReviewResult the value for review_result.fail_analysis_review_result
     *
     * @mbggenerated
     */
    public void setFailAnalysisReviewResult(Integer failAnalysisReviewResult) {
        this.failAnalysisReviewResult = failAnalysisReviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_result.risk_review_result
     *
     * @return the value of review_result.risk_review_result
     *
     * @mbggenerated
     */
    public Integer getRiskReviewResult() {
        return riskReviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_result.risk_review_result
     *
     * @param riskReviewResult the value for review_result.risk_review_result
     *
     * @mbggenerated
     */
    public void setRiskReviewResult(Integer riskReviewResult) {
        this.riskReviewResult = riskReviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review_result.fmea_id
     *
     * @return the value of review_result.fmea_id
     *
     * @mbggenerated
     */
    public Integer getFmeaId() {
        return fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review_result.fmea_id
     *
     * @param fmeaId the value for review_result.fmea_id
     *
     * @mbggenerated
     */
    public void setFmeaId(Integer fmeaId) {
        this.fmeaId = fmeaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_result
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", functionReviewResult=").append(functionReviewResult);
        sb.append(", failAnalysisReviewResult=").append(failAnalysisReviewResult);
        sb.append(", riskReviewResult=").append(riskReviewResult);
        sb.append(", fmeaId=").append(fmeaId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}