package com.rb.fmea.entities;

import java.io.Serializable;

public class RolePerm implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_perm.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_perm.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_perm.perm_id
     *
     * @mbggenerated
     */
    private Integer permId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_perm
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_perm.id
     *
     * @return the value of role_perm.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_perm.id
     *
     * @param id the value for role_perm.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_perm.role_id
     *
     * @return the value of role_perm.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_perm.role_id
     *
     * @param roleId the value for role_perm.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_perm.perm_id
     *
     * @return the value of role_perm.perm_id
     *
     * @mbggenerated
     */
    public Integer getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_perm.perm_id
     *
     * @param permId the value for role_perm.perm_id
     *
     * @mbggenerated
     */
    public void setPermId(Integer permId) {
        this.permId = permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_perm
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", permId=").append(permId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}