package com.rb.fmea.entities;

import java.io.Serializable;

public class SqliteSequence implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sqlite_sequence.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sqlite_sequence.seq
     *
     * @mbggenerated
     */
    private String seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sqlite_sequence
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sqlite_sequence.name
     *
     * @return the value of sqlite_sequence.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sqlite_sequence.name
     *
     * @param name the value for sqlite_sequence.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sqlite_sequence.seq
     *
     * @return the value of sqlite_sequence.seq
     *
     * @mbggenerated
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sqlite_sequence.seq
     *
     * @param seq the value for sqlite_sequence.seq
     *
     * @mbggenerated
     */
    public void setSeq(String seq) {
        this.seq = seq == null ? null : seq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqlite_sequence
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", seq=").append(seq);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}