package com.rb.fmea.dao;

import com.rb.fmea.entities.ApMonitor;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ApMonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_monitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_monitor
     *
     * @mbggenerated
     */
    int insert(ApMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_monitor
     *
     * @mbggenerated
     */
    ApMonitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_monitor
     *
     * @mbggenerated
     */
    List<ApMonitor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_monitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApMonitor record);

    /**
     * @Author yyk
     * @Description //TODO 查询一个fmea下的ap监控值
     * @Date 2020/6/10 15:52
     * @Param [fmeaId]
     * @return java.util.List<com.rb.fmea.entities.ApMonitor>
     **/
    List<ApMonitor> selectOneFmea(int fmeaId);
}