package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaFailAnalysis;
import com.rb.fmea.entities.FmeaFailAnalysisRelate;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FmeaFailAnalysisRelateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis_relate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis_relate
     *
     * @mbggenerated
     */
    int insert(FmeaFailAnalysisRelate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis_relate
     *
     * @mbggenerated
     */
    FmeaFailAnalysisRelate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis_relate
     *
     * @mbggenerated
     */
    List<FmeaFailAnalysisRelate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis_relate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaFailAnalysisRelate record);

    /**
     * @Author yyk
     * @Description //TODO 判断关系是否已经建立
     * @Date 2020/5/29 13:29
     * @Param [parentFailAnalysisId, nextFailAnalysisId]
     * @return com.rb.fmea.entities.FmeaFailAnalysisRelate
     **/
    FmeaFailAnalysisRelate selectByfailAnalysisSuperiorIdAndFailAnalysisNextId(@Param("parentFailAnalysisId") int parentFailAnalysisId, @Param("nextFailAnalysisId") int nextFailAnalysisId);

    /**
     * @Author yyk
     * @Description //TODO 查询当前分析模式的上级分析模式
     * @Date 2020/6/1 11:20
     * @Param [id]
     * @return java.util.List<com.rb.fmea.entities.FmeaFailAnalysis>
     **/
    List<FmeaFailAnalysis> selectByFailAnalysisNextId(Integer nextFailAnalysisId);

    /**
     * @Author yyk
     * @Description //TODO 查询当前分析模式的下级分析模式
     * @Date 2020/6/1 11:21
     * @Param [id]
     * @return java.util.List<com.rb.fmea.entities.FmeaFailAnalysis>
     **/
    List<FmeaFailAnalysis> selectByfailAnalysisSuperiorId(Integer superiorFailAnalysisId);
}