package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaMilestoneTime;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface FmeaMilestoneTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_milestone_time
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_milestone_time
     *
     * @mbggenerated
     */
    int insert(FmeaMilestoneTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_milestone_time
     *
     * @mbggenerated
     */
    FmeaMilestoneTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_milestone_time
     *
     * @mbggenerated
     */
    List<FmeaMilestoneTime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_milestone_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaMilestoneTime record);

    /**
     * @Author yyk
     * @Description //TODO 根据fmeaid查询
     * @Date 2020/6/3 16:23
     * @Param [fmeaId]
     * @return com.rb.fmea.entities.FmeaMilestoneTime
     **/
    FmeaMilestoneTime selectByFmeaId(int fmeaId);
}