package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaResume;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface FmeaResumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    int insert(FmeaResume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    FmeaResume selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    List<FmeaResume> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_resume
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaResume record);
}