package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaType;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface FmeaTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type
     *
     * @mbggenerated
     */
    int insert(FmeaType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type
     *
     * @mbggenerated
     */
    FmeaType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type
     *
     * @mbggenerated
     */
    List<FmeaType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaType record);

    List<FmeaType> selectPage(@Param("name") String name, @Param("page") int page, @Param("limit") int limit);

    int count(String name);
}