package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaTypeProduct;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface FmeaTypeProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type_product
     *
     * @mbggenerated
     */
    int insert(FmeaTypeProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type_product
     *
     * @mbggenerated
     */
    FmeaTypeProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type_product
     *
     * @mbggenerated
     */
    List<FmeaTypeProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_type_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaTypeProduct record);

    /**
     * @Author yyk
     * @Description //TODO 在产品下查询
     * @Date 2020/6/19 10:57
     * @Param [productId]
     * @return java.util.List<com.rb.fmea.entities.FmeaTypeProduct>
     **/
    List<FmeaTypeProduct> selectByProductId(int productId);
}