package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaFailAnalysis;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.data.annotation.QueryAnnotation;

import java.util.List;
@Mapper
public interface FmeaFailAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis
     *
     * @mbggenerated
     */
    int insert(FmeaFailAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis
     *
     * @mbggenerated
     */
    FmeaFailAnalysis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis
     *
     * @mbggenerated
     */
    List<FmeaFailAnalysis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_fail_analysis
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaFailAnalysis record);

    /**
     * @Author yyk
     * @Description //TODO 根据结构id查询失效分析
     * @Date 2020/6/1 10:23
     * @Param
     * @return
     **/

    List<FmeaFailAnalysis> selectFailAnalysisByStructId(int structureId);

    /**
     * @Author yyk
     * @Description //TODO 查询一个结构下的所有失效分析
     * @Date 2020/6/1 15:43
     * @Param [structureId]
     * @return java.util.List<com.rb.fmea.entities.FmeaFailAnalysis>
     **/
    List<FmeaFailAnalysis> selectOneStructure(int structureId);

    /**
     * @Author yyk
     * @Description //TODO 查询当前失效分析对应功能的的下级关联功能的所有失效分析
     * @Date 2020/6/1 15:55
     * @Param [fmeaFailAnalysisId]
     * @return java.util.List<com.rb.fmea.entities.FmeaFailAnalysis>
     **/
    List<FmeaFailAnalysis> selectNextFunction(int fmeaFailAnalysisId);
}