package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaMeasures;
import org.apache.ibatis.annotations.Mapper;

import javax.annotation.Resource;
import java.util.List;
@Mapper
public interface FmeaMeasuresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_measures
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_measures
     *
     * @mbggenerated
     */
    int insert(FmeaMeasures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_measures
     *
     * @mbggenerated
     */
    FmeaMeasures selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_measures
     *
     * @mbggenerated
     */
    List<FmeaMeasures> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_measures
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaMeasures record);
}