package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaBasicInformation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface FmeaBasicInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_basic_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_basic_information
     *
     * @mbggenerated
     */
    int insert(FmeaBasicInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_basic_information
     *
     * @mbggenerated
     */
    FmeaBasicInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_basic_information
     *
     * @mbggenerated
     */
    List<FmeaBasicInformation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_basic_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaBasicInformation record);

    /**
     * @Author yyk
     * @Description //TODO 根据fmeaid查询对应的基础信息
     * @Date 2020/6/3 15:29
     * @Param [fmeaId]
     * @return com.rb.fmea.entities.FmeaBasicInformation
     **/
    FmeaBasicInformation selectByFmeaId(int fmeaId);
}