package com.rb.fmea.dao;

import com.rb.fmea.dto.FmeaDto;
import com.rb.fmea.entities.Fmea;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface FmeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea
     *
     * @mbggenerated
     */
    int insert(Fmea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea
     *
     * @mbggenerated
     */
    Fmea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea
     *
     * @mbggenerated
     */
    List<Fmea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fmea record);

    /**
     * @Author yyk
     * @Description //TODO 查询所有基础fmea
     * @Date 2020/5/21 10:29
     * @Param []
     * @return java.util.List<com.rb.fmea.entities.Fmea>
     **/
   // @Select("select id, fmea_name, fmea_desc, product_id, superior_id from fmea where superior_id=0")
    List<Fmea> selectBasicFmea();

    /**
     * @Author yyk
     * @Description //TODO 查询一个产品下对应的基础,家族,新品fmea
     * @Date 2020/5/21 14:06
     * @Param [productId]
     * @return java.util.List<com.rb.fmea.entities.Fmea>
     **/
    List<FmeaDto> selectByProductId(@Param("productId") int productId, @Param("fmeaId") int fmeaId);
}