package com.rb.fmea.dao;

import com.rb.fmea.dto.FmeaStructureDto;
import com.rb.fmea.dto.StructureFunctionDto;
import com.rb.fmea.entities.FmeaFunctionRelate;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface FmeaFunctionRelateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_function_relate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_function_relate
     *
     * @mbggenerated
     */
    int insert(FmeaFunctionRelate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_function_relate
     *
     * @mbggenerated
     */
    FmeaFunctionRelate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_function_relate
     *
     * @mbggenerated
     */
    List<FmeaFunctionRelate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_function_relate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaFunctionRelate record);

    /**
     * @Author yyk
     * @Description //TODO 根据结构查询当前结构上级结构对应的功能
     * @Date 2020/5/26 10:00
     * @Param [structureId]
     * @return java.util.List<com.rb.fmea.dto.FmeaStructureDto>
     **/
    List<StructureFunctionDto> selectParentByStructureId(int structureId);


    /**
     * @Author yyk
     * @Description //TODO 根据结构查询当前结构下级结构对应的功能
     * @Date 2020/5/26 10:00
     * @Param [structureId]
     * @return java.util.List<com.rb.fmea.dto.FmeaStructureDto>
     **/
    List<StructureFunctionDto> selectNextByStructureId(int structureId);

    FmeaFunctionRelate selectBySuperiorIdAndNextId(int superiorId, int nextId);
}