package com.rb.fmea.dao;

import com.rb.fmea.entities.FmeaAp;
import java.util.List;

public interface FmeaApMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    int insert(FmeaAp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    FmeaAp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    List<FmeaAp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fmea_ap
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FmeaAp record);
}