package com.rb.fmea.dao;

import com.rb.fmea.entities.FunctionStandard;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface FunctionStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_standard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_standard
     *
     * @mbggenerated
     */
    int insert(FunctionStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_standard
     *
     * @mbggenerated
     */
    FunctionStandard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_standard
     *
     * @mbggenerated
     */
    List<FunctionStandard> selectAll(int type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function_standard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FunctionStandard record);

    /**
     * @Author yyk
     * @Description //TODO 分页查询
     * @Date 2020/5/23 14:42
     * @Param [page, limit, functionStandard]
     * @return java.util.List<com.rb.fmea.entities.FunctionStandard>
     **/
    List<FunctionStandard> select(@Param("page") int page, @Param("limit") int limit, @Param("functionStandard") FunctionStandard functionStandard);

    /**
     * @Author yyk
     * @Description //TODO 查询总条数
     * @Date 2020/5/23 14:43
     * @Param [functionStandard]
     * @return int
     **/
    int count(@Param("functionStandard") FunctionStandard functionStandard);

    /**
     * @Author yyk
     * @Description //TODO 根据拼接字段模糊查询
     * @Date 2020/5/29 14:15
     * @Param [integrate]
     * @return java.util.List<com.rb.fmea.entities.FunctionStandard>
     **/
    List<FunctionStandard> selectByIntegrateLike(String integrate);
}