package com.rb.fmea.dao;

import com.rb.fmea.entities.MeasuresMonitor;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface MeasuresMonitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measures _monitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measures _monitor
     *
     * @mbggenerated
     */
    int insert(MeasuresMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measures _monitor
     *
     * @mbggenerated
     */
    MeasuresMonitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measures _monitor
     *
     * @mbggenerated
     */
    List<MeasuresMonitor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measures _monitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MeasuresMonitor record);

    /**
     * @Author yyk
     * @Description //TODO 措施监控每种类型每个月数据
     * @Date 2020/6/20 15:00
     * @Param [level, productId]
     * @return java.util.List<com.rb.fmea.entities.MeasuresMonitor>
     **/
    List<MeasuresMonitor> selectByLevel(@Param("level") String level, @Param("productId") int productId);

    /**
     * @Author yyk
     * @Description //TODO 查询当前产品的措施监控的月份
     * @Date 2020/6/20 15:30
     * @Param [productId]
     * @return java.util.List<java.lang.Integer>
     **/
    List<Integer> selectMonByProductId(int productId);

    /**
     * @Author yyk
     * @Description //TODO 根据月份和产品id查询每个类型每个月的总数
     * @Date 2020/6/20 15:34
     * @Param [开放, integer, productId]
     * @return java.util.List<com.rb.fmea.entities.MeasuresMonitor>
     **/
    Integer selectByLevelAndMonAndProductId(@Param("level") String level, @Param("month") Integer month, @Param("productId") int productId);
}