package com.rb.fmea.dao;

import com.rb.fmea.entities.Perm;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbggenerated
     */
    int insert(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbggenerated
     */
    Perm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbggenerated
     */
    List<Perm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Perm record);

    /**
     * @Author yyk
     * @Description //TODO 根据用户id查询权限
     * @Date 2020/5/28 14:56
     * @Param [id]
     * @return java.util.List<com.rb.fmea.entities.Perm>
     **/
    List<Perm> selectPermByUserId(Integer id);
}