package com.rb.fmea.dao;

import com.rb.fmea.entities.Product;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    /**
     * @Author yyk
     * @Description //TODO 根据名称分页查询
     * @Date 2020/5/20 17:23
     * @Param [name, page, limit]
     * @return java.util.List<com.rb.fmea.entities.Product>
     **/
    List<Product> selectByNameAndPage(String name, int page, int limit);

    /**
     * @Author yyk
     * @Description //TODO 根据名称查询总数
     * @Date 2020/5/20 17:23
     * @Param [name]
     * @return int
     **/
    int count(String name);
}