package com.rb.fmea.dao;

import com.rb.fmea.entities.ReviewResult;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ReviewResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_result
     *
     * @mbggenerated
     */
    int insert(ReviewResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_result
     *
     * @mbggenerated
     */
    ReviewResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_result
     *
     * @mbggenerated
     */
    List<ReviewResult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReviewResult record);

    List<ReviewResult> selectByPage(@Param("page") int page, @Param("limit") int limit, @Param("productId") int productId);

    int count(int productId);


    ReviewResult selectByFmeaId(int fmeaId);

    ReviewResult selectByReviewId(int reviewId);
}