package com.rb.fmea.dao;

import com.rb.fmea.entities.SqliteSequence;
import java.util.List;

public interface SqliteSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqlite_sequence
     *
     * @mbggenerated
     */
    int insert(SqliteSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sqlite_sequence
     *
     * @mbggenerated
     */
    List<SqliteSequence> selectAll();
}